set(PACKAGE_VERSION "1.0.0")

if("${PACKAGE_FIND_VERSION}" VERSION_EQUAL "1.0.0")
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
    set(PACKAGE_VERSION_EXACT TRUE)
elseif("${PACKAGE_FIND_VERSION}" VERSION_LESS "1.0.0")
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
    set(PACKAGE_VERSION_EXACT FALSE)
endif()