# Файл проверки версии
set(PACKAGE_VERSION "1.0.0")

# Проверка совместимости версий CMake
if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
  set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
  if(PACKAGE_FIND_VERSION STREQUAL PACKAGE_VERSION)
    set(PACKAGE_VERSION_EXACT TRUE)
  endif()
endif()

# Проверка архитектуры (если важно)
if(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64" OR CMAKE_SYSTEM_PROCESSOR STREQUAL "AMD64")
  set(ARCH_COMPATIBLE TRUE)
else()
  set(ARCH_COMPATIBLE FALSE)
endif()

if(NOT ARCH_COMPATIBLE)
  set(PACKAGE_VERSION_UNSUITABLE TRUE)
endif()